import Foundation

struct GhosttyConfigBridge {
    static func parse(from path: String) -> [String: String] {
        guard let content = try? String(contentsOfFile: path, encoding: .utf8) else {
            return [:]
        }

        var config: [String: String] = [:]

        for line in content.components(separatedBy: .newlines) {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            guard !trimmed.hasPrefix("#"), !trimmed.isEmpty else { continue }

            let parts = trimmed.split(separator: "=", maxSplits: 1)
            if parts.count == 2 {
                let key = parts[0].trimmingCharacters(in: .whitespaces)
                let value = parts[1].trimmingCharacters(in: .whitespaces)
                config[key] = value
            }
        }

        return config
    }

    static func merge(fasty: [String: Any], ghostty: [String: String]) -> [String: String] {
        var result = ghostty
        for (key, value) in fasty {
            result[key] = "\(value)"
        }
        return result
    }

    static func exportToGhosttyConfig(_ settings: [String: Any]) -> String {
        var lines: [String] = ["# Generated by Fasty"]
        for (key, value) in settings.sorted(by: { $0.key < $1.key }) {
            lines.append("\(key) = \(value)")
        }
        return lines.joined(separator: "\n")
    }
}
